# accelerate_config.yaml

compute_environment: LOCAL_MACHINE
distributed_type: MULTI_GPU
mixed_precision: bf16
use_cpu: false

# Tell Accelerate how many GPUs / processes
num_processes: 4
num_machines: 1



